### ISSUE TITLE
Implement keyboard shortcuts in proper atom api format

### ISSUE THREAD

**Issue by zenopopovici** [olegberman/atom-shortcuts#1]
The keyboard shortcuts are impossible to override right now. This causes clashes with other extensions. 
Also the keyboard shortcut doesn't appear in the atom keymap list.

**Comment by olegberman** [comment]
Okay, since I've already got 140 downloads I will try to make it right. 

The issue that I was having is that I couldn't figure out how to catch `keyup`and `keydown` separately through normal atom keymaps (as it only catches a complete stroke of a shortcut). The convenience of being able to hide the cheatsheet by just releasing a button overdrew the will to make it right at the moment. Only for that reason I've chosen a shortcut that is comfortable for your fingers and probably not very commonly used. 

I will look into Atom's API again, maybe I'm missing something. Thanks so much for your interest!

**Comment by zenopopovici** [comment]
I actually hate it that I do have to keep it pressed, you do need to scan for what you need :)
But I guess usage highly differs. The other problem with the current implementation is that it also disregards 3 key commands any shortcut that has the ctr+`+any_other_key combination will open the popup. Which is bad.

You could set a timer for it or just implement a simple toggle. 

Great work tough, I'm recommending it to newcomers to Atom.

**Comment by pbraga** [comment]
+1 for not being able to override the shortcut.
In Portuguese keyboards the back-tick need a shift press...so i cannot use this plugin at all....
Do like the idea of a pop up cheatsheet

**Comment by Rosefalk** [comment]
Can't use this with a Danish keyboard since it requires shift.

**Comment by witwit** [comment]
Same here, backtick is a bad choice for toggle

**Comment by olegberman** [comment]
2,628 installs! Definitely will look  into this.

**Comment by nickooolas** [comment]
Everybody got the ctrl + ` for lots others extensions. Would be great to be able to change it. BTW: 3,227 installs!

**Comment by ghost** [comment]
+1 and 4,948 installs.

**Comment by ethernal** [comment]
+1 
6,815 and counting - we need a proper fork probably. OR a fix. I have no idea how packages for atom are made but... maybe...

BTW  ctrl+` is default for console components and for devs/gamers? that's quite standard I think.

**Comment by progand** [comment]
I've found similar tool https://github.com/jkasky/atom-keybinding-cheatsheet

**Comment by olegberman** [comment]
Do you guys still need this extension? Vote for the trigger shortcut that you want to use. 

P.S. 5 issues / 0 forks?

**Comment by progand** [comment]
I suggest `Ctrl+Alt+/`

**Comment by Frederic-C** [comment]
It displays only by pressing "ctrl", which is super anoying. Unable to use it :/
